baseurl = "http://hugo.spf13.com/"
title = "A Blog"
author = "A Xing"
copyright = "Copyright (c) 2008 - 2014"
canonifyurls = true
paginate = 10


[params]
    author = "A Xing"
    locale = "en-US"

[taxonomies]
    about = "abouts"
    draft = "drafts"
    essay = "essays"
    category = "categories"
    tag = "tags"
    

